services:
  - type: web
    name: DevScore-app
    env: python
    # The build command should use the venv's pip, executed from the repo root (since Root Dir is DevScore)
    buildCommand: /opt/render/project/src/DevScore/.venv/bin/pip install -r app/requirements.txt

    # The start command should use the venv's python to run uvicorn
    # And crucially, Uvicorn needs to be invoked in a way that it can find DevScore.app.score
    # by running from the repo root context.
    startCommand: /opt/render/project/src/.venv/bin/python -m uvicorn DevScore.app.score:app --host=0.0.0.0 --port=10000

    envVars:
      - key: PORT
        value: 10000